server:
  port: 7070
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
app:
  jwt:
    secret: rentalJwtSecretKey
    expiresIn: 86400000
  authorities:
    USER: USER
    ADMIN: ADMIN
