# github workflow for deploying this spring boot app to azure web app
# runs ./mvnw azure-spring-apps:deploy to deploy to azure web app

# Path: .github\workflows\azure-maven-deploy.yml
# # For more samples to get started with GitHub Action workflows to deploy to Azure:

name: Build and deploy a maven app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: rentalresidence # set this to the name of your Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Set MongoDB URI
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        run: ./mvnw azure-webapp:deploy
